name: "Run bot"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 * * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Initialize Shell
      run: nix-shell --command echo
    - name: Run
      run: ./dog-bot.sh
